"""added failed_login_attempts and is_locked_until security field for password protection to user model

Revision ID: 043a51e0082f
Revises: 341138354919
Create Date: 2026-03-01 16:55:47.631323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043a51e0082f'
down_revision: Union[str, Sequence[str], None] = '341138354919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
