"""add auth security fields to user model

Revision ID: 9f83482e2478
Revises: 16e6b57f7576
Create Date: 2026-02-22 22:48:06.625957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f83482e2478'
down_revision: Union[str, Sequence[str], None] = '16e6b57f7576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'is_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
