"""add orders and order_items_tables

Revision ID: a7080871d985
Revises: 341138354919
Create Date: 2026-03-07 12:53:12.660817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7080871d985'
down_revision: Union[str, Sequence[str], None] = '341138354919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('is_locked_until', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
